import type { Dashboard } from './types';

export const demoDashboard: Dashboard = {
  privacyEpoch: 0,
  edition: {
    id: 'edition-demo',
    label: 'Morning edition',
    generatedAt: '2026-07-26T08:00:00Z',
    nextEditionAt: null,
    summary:
      'Four useful updates across your sources. Two themes are worth a closer look; everything else can wait.',
  },
  items: [
    {
      id: 'post-local-ai',
      sourceId: 'source-rss-ai',
      source: 'Practical AI Notes',
      author: 'Mira Chen',
      title: 'Smaller local models are becoming better everyday tools',
      summary:
        'A new evaluation finds that smaller quantized models now handle routine extraction and summarization reliably when tasks use constrained schemas and focused context.',
      commentOverview:
        'Readers broadly agree on the privacy benefit. The main disagreement is whether 8 GB machines provide a comfortable experience.',
      summaryMethod: 'fixture',
      summaryProvider: 'demo-fixture',
      summaryUncertainty: 'Demonstration content; connect a real source for current evidence.',
      publishedAt: '2026-07-26T06:40:00Z',
      publishedTimeKind: 'published',
      reason: 'Demonstration why-shown explanation · local AI topic',
      topic: 'Local AI',
      importance: 0.91,
      evidence: [
        {
          source: 'Practical AI Notes',
          author: 'Mira Chen',
          publishedAt: '2026-07-26T06:40:00Z',
          timestampKind: 'published',
          excerpt: 'The largest gains came from better task framing, not larger parameter counts.',
          canonicalUrl: 'https://example.com/local-models',
        },
      ],
    },
    {
      id: 'post-civic',
      sourceId: 'source-mastodon',
      source: 'Mastodon · technology',
      author: '@fieldnotes@social.example',
      title: 'A calmer way to follow local planning updates',
      summary:
        'A community group published a machine-readable city planning feed and a plain-language weekly recap, making meeting changes easier to track.',
      commentOverview:
        'Replies add two missing neighborhood feeds and ask for accessible calendar exports. No major disagreement appears.',
      summaryMethod: 'fixture',
      summaryProvider: 'demo-fixture',
      summaryUncertainty: 'Demonstration content; connect a real source for current evidence.',
      publishedAt: '2026-07-26T05:25:00Z',
      publishedTimeKind: 'published',
      reason: 'Demonstration why-shown explanation · civic topic',
      topic: 'Civic technology',
      importance: 0.84,
      evidence: [
        {
          source: 'Mastodon · technology',
          author: '@fieldnotes@social.example',
          publishedAt: '2026-07-26T05:25:00Z',
          timestampKind: 'published',
          excerpt: 'The feed includes cancellations, agenda changes, and accessible meeting links.',
          canonicalUrl: 'https://social.example/@fieldnotes/1',
        },
      ],
    },
    {
      id: 'post-web',
      sourceId: 'source-bluesky',
      source: 'Bluesky · Following',
      author: 'Elena Park',
      title: 'Browsers add a practical privacy control for local network access',
      summary:
        'A proposed browser permission would make websites ask before reaching devices and services on a private network.',
      commentOverview:
        'Security engineers support the direction but note that clear permission copy and enterprise migration will matter.',
      summaryMethod: 'fixture',
      summaryProvider: 'demo-fixture',
      summaryUncertainty: 'Demonstration content; connect a real source for current evidence.',
      publishedAt: '2026-07-26T04:10:00Z',
      publishedTimeKind: 'published',
      reason: 'Demonstration why-shown explanation · web privacy topic',
      topic: 'Web privacy',
      importance: 0.79,
      evidence: [
        {
          source: 'Bluesky · Following',
          author: 'Elena Park',
          publishedAt: '2026-07-26T04:10:00Z',
          timestampKind: 'published',
          excerpt:
            'Private network requests should be visible user decisions rather than ambient capability.',
          canonicalUrl: 'https://bsky.app/profile/example/post/1',
        },
      ],
    },
    {
      id: 'post-design',
      sourceId: 'source-rss-design',
      source: 'Humane Interfaces',
      author: 'Ari Bell',
      title: 'Designing software with a natural stopping point',
      summary:
        'Finite editions and stable ordering help readers complete a review session without feeling that unseen content is accumulating.',
      commentOverview:
        'The discussion favors scheduled editions; several readers want a deliberate manual refresh for urgent days.',
      summaryMethod: 'fixture',
      summaryProvider: 'demo-fixture',
      summaryUncertainty: 'Demonstration content; connect a real source for current evidence.',
      publishedAt: '2026-07-25T22:15:00Z',
      publishedTimeKind: 'published',
      reason: 'Demonstration why-shown explanation · calm design topic',
      topic: 'Calm design',
      importance: 0.7,
      evidence: [
        {
          source: 'Humane Interfaces',
          author: 'Ari Bell',
          publishedAt: '2026-07-25T22:15:00Z',
          timestampKind: 'published',
          excerpt:
            'Completion is a feature: a product should be able to say there is nothing more to consume right now.',
          canonicalUrl: 'https://example.com/stopping-points',
        },
      ],
    },
  ],
  trends: [
    {
      id: 'trend-local-first',
      label: 'Local-first tools are narrowing the convenience gap',
      summary:
        'Independent posts point to better small models and safer browser boundaries. The shared direction is more capable software without default cloud dependence.',
      sourceCount: 3,
      confidence: 'supported',
      method: 'fixture',
      evidenceIds: ['post-local-ai', 'post-web', 'post-design'],
    },
    {
      id: 'trend-calm-tech',
      label: 'Deliberate information routines',
      summary:
        'Feeds, summaries, and finite editions are being used to make important updates easier to follow without continuous checking.',
      sourceCount: 2,
      confidence: 'emerging',
      method: 'fixture',
      evidenceIds: ['post-civic', 'post-design'],
    },
  ],
  sources: [
    {
      id: 'source-rss-ai',
      kind: 'rss',
      label: 'Practical AI Notes',
      detail: 'RSS · publisher feed',
      status: 'healthy',
      healthDetail: 'Fixture RSS source is ready.',
      commentsStatus: 'unavailable',
      commentsTruncated: false,
      syncFinality: 'complete',
      lastSync: '2026-07-26T07:57:00Z',
      nextSync: null,
      itemCount: 12,
    },
    {
      id: 'source-mastodon',
      kind: 'mastodon',
      label: 'Mastodon',
      detail: 'Demo connector · no production account is connected',
      status: 'transient',
      healthDetail: 'Demo fixture only; OAuth is not available in this build.',
      commentsStatus: 'partial',
      commentsTruncated: true,
      syncFinality: 'partial',
      lastSync: '2026-07-26T07:56:00Z',
      nextSync: null,
      itemCount: 8,
    },
    {
      id: 'source-bluesky',
      kind: 'bluesky',
      label: 'Bluesky',
      detail: 'Demo connector · no production account is connected',
      status: 'transient',
      healthDetail: 'Demo fixture only; OAuth is not available in this build.',
      commentsStatus: 'partial',
      commentsTruncated: true,
      syncFinality: 'partial',
      lastSync: '2026-07-26T07:56:00Z',
      nextSync: null,
      itemCount: 9,
    },
    {
      id: 'source-rss-design',
      kind: 'rss',
      label: 'Humane Interfaces',
      detail: 'RSS · publisher feed',
      status: 'healthy',
      healthDetail: 'Fixture RSS source is ready.',
      commentsStatus: 'unavailable',
      commentsTruncated: false,
      syncFinality: 'complete',
      lastSync: '2026-07-26T07:57:00Z',
      nextSync: null,
      itemCount: 6,
    },
  ],
  activity: [
    {
      id: 'activity-1',
      kind: 'digest',
      status: 'complete',
      message: 'Morning edition created from 35 items',
      occurredAt: '2026-07-26T08:00:00Z',
    },
    {
      id: 'activity-2',
      kind: 'sync',
      status: 'complete',
      message: '2 RSS sources synchronized',
      occurredAt: '2026-07-26T07:57:00Z',
    },
  ],
  settings: {
    scheduleEnabled: false,
    scheduleHour: 8,
    quietHoursStart: 21,
    quietHoursEnd: 7,
    retentionDays: 30,
    remoteMedia: false,
    localOnly: true,
    feedbackCount: 0,
    selectedModel: '',
    rankingPaused: false,
  },
  model: {
    provider: 'Ollama-compatible',
    state: 'runtime_unavailable',
    model: null,
    digest: null,
    sizeBytes: null,
    parameterSize: null,
    quantization: null,
    runtimeVersion: null,
    structuredOutput: false,
    endpoint: 'http://127.0.0.1:11434',
    fallbackAvailable: true,
    detail:
      'Deterministic local fallback is active. No content leaves this computer for inference.',
  },
  host: {
    os: 'browser preview',
    arch: 'unknown',
    totalMemoryGb: 0,
    availableMemoryGb: 0,
    logicalCpuCount: navigator.hardwareConcurrency || 0,
    gpu: { state: 'unknown', detail: 'No reliable browser accelerator probe.' },
    battery: { state: 'unknown', detail: 'Browser preview does not inspect power state.' },
    meteredNetwork: { state: 'unknown', detail: 'Downloads always require user action.' },
    localRuntime: {
      state: 'unavailable',
      detail: 'Desktop runtime is not active; extractive fallback is available.',
    },
    recommendedProfile: {
      id: 'cpu-basic',
      title: 'CPU / basic',
      generationModel: '3B Q4 local model or extractive fallback',
      embeddingModel: 'Disabled until a local capability probe passes',
      contextWindow: 4096,
      maxConcurrentRequests: 1,
      rationale:
        'Browser preview cannot inspect system capacity, so it uses the conservative profile.',
      requiresExplicitDownload: true,
    },
  },
  connectors: [
    {
      kind: 'rss',
      label: 'RSS / Atom',
      availability: 'available',
      detail: 'Official feed URLs; read-only and available now.',
      unmetPrerequisite: null,
      readOnly: true,
      supportsComments: false,
      requiresOauth: false,
    },
    {
      kind: 'mastodon',
      label: 'Mastodon',
      availability: 'validation_required',
      detail: 'Official read-only home timeline and bounded context are planned.',
      unmetPrerequisite:
        'Instance OAuth compatibility and provider policy review are required before connection is enabled.',
      readOnly: true,
      supportsComments: true,
      requiresOauth: true,
    },
    {
      kind: 'bluesky',
      label: 'Bluesky',
      availability: 'blocked',
      detail: 'Official read-only timeline and bounded thread support are planned.',
      unmetPrerequisite:
        'A public HTTPS client-metadata/policy origin, owned native callback, and exact permission validation are required.',
      readOnly: true,
      supportsComments: true,
      requiresOauth: true,
    },
  ],
  runner: {
    active: false,
    inFlight: false,
    lastAttemptAt: null,
    lastSuccessAt: null,
    nextScheduledAt: null,
    lastOutcome: 'idle',
    detail: 'Browser preview has no resident Rust runner.',
  },
};
